"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u395&evabi2_x1#9$x9qfpo#8hfzg0&qj79gnn0j=!9it9_qm@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "corsheaders",

    # Local apps
    "core",
    "app_config",
    "banners",
    "xtream",
    "astra",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (archivos generados en runtime: salidas HLS del transcoder, etc.)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Transcoder HLS (prueba técnica, ver docs/transcoder_hls.md) ---
# Ruta del binario de FFmpeg. Se deja configurable por entorno para no
# asumir que está en el PATH del sistema en todos los equipos/servidores.
FFMPEG_BIN = config("FFMPEG_BIN", default="ffmpeg")

# Ruta del binario de ffprobe (viene junto a FFmpeg). Se usa para leer el
# códec original del canal y decidir entre remux y transcode.
FFPROBE_BIN = config("FFPROBE_BIN", default="ffprobe")

# Carpeta raíz donde el transcoder escribe cada salida HLS: MEDIA/hls/<stream_id>/
HLS_ROOT = MEDIA_ROOT / "hls"

# Segundos que un index.m3u8 se considera "activo/reciente" antes de
# permitir relanzar un proceso para el mismo stream_id (evita duplicados).
HLS_ACTIVE_TTL_SECONDS = config("HLS_ACTIVE_TTL_SECONDS", default=30, cast=int)

# Límite de procesos FFmpeg simultáneos. Si se alcanza, el endpoint responde
# transcoder_busy en vez de lanzar más procesos y saturar el servidor.
MAX_CONCURRENT_TRANSCODES = config("MAX_CONCURRENT_TRANSCODES", default=5, cast=int)

# Segmentos .ts mínimos que debe haber generado FFmpeg antes de dar el HLS
# por "listo" y responder al player (Android falla si recibe la URL demasiado
# pronto). Usado por wait_for_hls_ready() y por el diagnóstico hls-status.
HLS_MIN_SEGMENTS = config("HLS_MIN_SEGMENTS", default=2, cast=int)

# Normalización móvil por framerate: un canal cuyo video se copiaría tal cual
# (remux / transcode_audio) pero que emite a MÁS de estos fps se recodifica a
# 720p30. El decoder de hardware del cel batalla con HD a 60fps (bloques /
# fotogramas soltados). Usado por transcoder.decide_mode().
MOBILE_TRANSCODE_MAX_FPS = config("MOBILE_TRANSCODE_MAX_FPS", default=30, cast=int)

# --- Astra playlist ---
ASTRA_PLAYLIST_URL = config("ASTRA_PLAYLIST_URL", default="")

# Limpieza automática: si la salida HLS de un stream no se actualiza en este
# tiempo (FFmpeg murió/estancado), se detiene el proceso y se borra la carpeta.
HLS_CLEANUP_TTL_SECONDS = config("HLS_CLEANUP_TTL_SECONDS", default=300, cast=int)

# Cada cuánto corre el hilo de limpieza en segundo plano.
HLS_CLEANUP_INTERVAL_SECONDS = config("HLS_CLEANUP_INTERVAL_SECONDS", default=60, cast=int)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
}